version: "3"
services:
    nginx:
        image: nginx
        depends_on:
            - php-fpm
        ports:
            - "8000:80"
        volumes:
            - ".:/home/docker"
            - "./nginxdir/default.conf:/etc/nginx/conf.d/default.conf"
            - "./html:/usr/share/nginx/html"
    
    php-fpm:
        build: phpdir
        volumes:
            - ".:/home/docker:rw"
            - "./html:/usr/share/nginx/html"
        ports:
            - "9000:9000"
        working_dir: "/home/docker"

    db:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin